---
abstract: 'Pure perl, Web-based and Pluggable Media Center Application'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Remedie
no_index:
  directory:
    - inc
    - t
requires:
  DateTime: 0
  Feed::Find: 0
  FindBin::libs: 0
  HTTP::Engine: 0
  JSON::XS: 0
  LWP::UserAgent: 0
  MIME::Types: 0
  Moose: 0
  Path::Class: 0
  Rose::DB: 0
  Rose::DB::Object: 0
  String::CamelCase: 0
  URI: 0
  XML::RSS::LibXML: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.1.0
